// Generated by gencpp from file map_creator/capability.msg
// DO NOT EDIT!


#ifndef MAP_CREATOR_MESSAGE_CAPABILITY_H
#define MAP_CREATOR_MESSAGE_CAPABILITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <map_creator/capShape.h>

namespace map_creator
{
template <class ContainerAllocator>
struct capability_
{
  typedef capability_<ContainerAllocator> Type;

  capability_()
    : header()
    , resolution(0.0)
    , capShapes()  {
    }
  capability_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , capShapes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef std::vector< ::map_creator::capShape_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::map_creator::capShape_<ContainerAllocator> >::other >  _capShapes_type;
  _capShapes_type capShapes;





  typedef boost::shared_ptr< ::map_creator::capability_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_creator::capability_<ContainerAllocator> const> ConstPtr;

}; // struct capability_

typedef ::map_creator::capability_<std::allocator<void> > capability;

typedef boost::shared_ptr< ::map_creator::capability > capabilityPtr;
typedef boost::shared_ptr< ::map_creator::capability const> capabilityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_creator::capability_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_creator::capability_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_creator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'map_creator': ['/home/alfredo/ros_ws/src/reuleaux/map_creator/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_creator::capability_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_creator::capability_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_creator::capability_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_creator::capability_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_creator::capability_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_creator::capability_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_creator::capability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dffe58c4981f75e1ef3876851c67ddd";
  }

  static const char* value(const ::map_creator::capability_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dffe58c4981f75eULL;
  static const uint64_t static_value2 = 0x1ef3876851c67dddULL;
};

template<class ContainerAllocator>
struct DataType< ::map_creator::capability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_creator/capability";
  }

  static const char* value(const ::map_creator::capability_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_creator::capability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 resolution\n"
"\n"
"map_creator/capShape[] capShapes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: map_creator/capShape\n"
"std_msgs/Header header\n"
"\n"
"float32 identifier\n"
"\n"
"float32 ri\n"
"\n"
"float32 angleSFE\n"
"\n"
"geometry_msgs/Pose pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::map_creator::capability_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_creator::capability_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.capShapes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct capability_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_creator::capability_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_creator::capability_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "capShapes[]" << std::endl;
    for (size_t i = 0; i < v.capShapes.size(); ++i)
    {
      s << indent << "  capShapes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::map_creator::capShape_<ContainerAllocator> >::stream(s, indent + "    ", v.capShapes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_CREATOR_MESSAGE_CAPABILITY_H
